import { useEffect, useState } from 'react'

export default function App() {
  // config.js is generated by the container entrypoint and identifies the
  // node that served this page (active-active demo).
  const [nodeId] = useState(() => window.__NODE_ID__ || 'unknown')
  const [lbNode, setLbNode] = useState(null)

  useEffect(() => {
    fetch('/healthz')
      .then((r) => r.text())
      .then((text) => setLbNode(text.trim()))
      .catch(() => setLbNode('unreachable'))
  }, [])

  return (
    <main className="page">
      <h1>nginx + React 19 — active-active</h1>
      <p>
        This page was served by <strong data-testid="node-id">{nodeId}</strong>
      </p>
      <p>
        <code>/healthz</code> answered by <strong>{lbNode ?? '…'}</strong>
      </p>
      <p className="hint">
        Reload the page — the load balancer round-robins across both nodes.
      </p>
    </main>
  )
}
